### ISSUE TITLE
Coach added by Instructor isn't enrolled in course

### ISSUE THREAD

**Issue by carsongee** [mitocw/edx-platform#48] opened 2015-08-13 16:59 UTC
I experienced this on edge.edx.  As an instructor I added a coach.  I logged in as the coach and received a page saying that I was not enrolled in any course.  I will test this in our sandbox as well and report back.

**Comment by pdpinch** [comment] 2015-08-23 22:35
Duplicate of #37

**Closed by pdpinch** 2015-08-23 22:35 UTC
Labels: CCX, duplicate
